// FIX: Removed self-import of `FileTree` which was conflicting with the type declared in this file.
export interface Message {
  id: string;
  role: 'user' | 'assistant';
  text: string;
  images?: {
    data: string; // base64 encoded image
    mimeType: string;
  }[];
  plan?: string[];
  fileChanges?: string[];
}

export type FileTree = Record<string, string>;

export interface Version {
  id: string;
  name: string;
  createdAt: Date;
  fileTree: FileTree;
  metadata?: {
    changeType?: 'creation' | 'modification' | 'deletion' | 'improvement' | 'bugfix' | 'feature' | 'refactor';
    severity?: 'minor' | 'major' | 'critical';
    filesChanged?: string[];
    isAutoGenerated?: boolean;
    aiMessage?: string;
  };
}

export interface Project {
  id: string;
  name: string;
  fileTree: FileTree;
  isPublic: boolean;
  updatedAt: Date;
  tags?: string[];
  category?: string;
  description?: string;
}

export type Language = 'en' | 'pt' | 'es';