import { createClient } from '@supabase/supabase-js';

// Configurações do Supabase usando apenas variáveis de ambiente
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables. Please check your .env.local file.');
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Tipos para o banco de dados
export interface DatabaseProject {
  id: string;
  name: string;
  file_tree: Record<string, string>;
  is_public: boolean;
  created_at: string;
  updated_at: string;
  user_id?: string;
  tags?: string[];
  category?: string;
  description?: string;
}

export interface DatabaseUser {
  id: string;
  email: string;
  created_at: string;
  updated_at: string;
  display_name?: string;
  avatar_url?: string;
}

export interface DatabaseVersion {
  id: string;
  project_id: string;
  name: string;
  file_tree: Record<string, string>;
  created_at: string;
  metadata?: {
    changeType?: 'creation' | 'modification' | 'deletion' | 'improvement' | 'bugfix' | 'feature' | 'refactor';
    severity?: 'minor' | 'major' | 'critical';
    filesChanged?: string[];
    isAutoGenerated?: boolean;
    aiMessage?: string;
  };
}